# Site wide configuration
title: "Unified Networking Lab"
description: "A software by Andrea Dainese"
locale: "en_US"
timezone: Europe/Rome
encoding: utf-8
logo: "logo_rr.png"
url: "http://www.unetlab.com"
disqus: "unetlab"
analytics: "UA-426446-18"

# Jekyll configuration
permalink: /:year/:month/:title/
#paginate: 10
markdown: kramdown
highlighter: pygments
sass:
    sass_dir: _sass
    style: compressed
gems:
- jekyll-sitemap

kramdown:
    auto_ids: true
    footnote_nr: 1
    entity_output: as_char
    toc_levels: 1..6
    use_coderay: false

# Authors
authors:
    andrea:
        name: Andrea Dainese
        display_name: Andrea
        email: andrea.dainese@gmail.com
        web: http://www.routereflector.com/
        twitter: adainese
        github: dainok
        linkedin: adainese
        gplus: AndreaDainese

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
