# Site wide configuration
title: "eve-ng (UNetLab 2.0)"
description: "Emulated Virtual Environment - Next Gen."
locale: "en_US"
timezone: Europe/Rome
encoding: utf-8
logo: "logo_eve.png"
url: "http://www.unetlab.com"
disqus: "unetlab"
analytics: "UA-426446-18"
posts_in_home: 10

# Jekyll configuration
permalink: /:year/:month/:title/
markdown: kramdown
highlighter: rouge
sass:
    sass_dir: _sass
    style: compressed
gems:
- jekyll-sitemap

kramdown:
    auto_ids: true
    footnote_nr: 1
    entity_output: as_char
    toc_levels: 1..6
    enable_coderay: false

# Authors
authors:
    andrea:
        name: Andrea Dainese
        title: Developer and Unetlab Creator
        display_name: Andrea
        email: andrea.dainese@gmail.com
        web: http://www.routereflector.com/
        twitter: adainese
        github: dainok
        linkedin: adainese
        gplus: AndreaDainese
    alain:
        name: Alain Degreffe 
        title: Developer and EVE creator
        display_name: Alain
        email: adegreffe@gmail.com
        linkedin: alaindegreffe
    michael:
        name: Michael Yandulov
        title: Project Manager and Community Releations / Networking expert and consultant
        display_name: Michael
        email: myandulov@gmail.com
        twitter: mike_yand
        linkedin: michaelyandulov
    uldis:
        name: Uldis Dzerkals
        title: Networking expert and consultant
        display_name: Uldis
        email: poisonfish@gmx.com
        linkedin: uldisdzerkals

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
